package com.flour.web.domain;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class DocumentPayment {


    //DOCUMENT_HOLIDAY(휴가 신청서 테이블)
    private String DOCUMENTHOLIDAYNUM;
    private String userIdennum;
    private String DOCUMENTHOLIDAYUSERNAME;
    private String DOCUMENTHOLIDAYUSERDEPARTMENT;
    private String DOCUMENTHOLIDAYTITLE;
    private String DOCUMENTHOLIDAYSORT;
    private String DOCUMENTHOLIDAYSUBMITDAY;
    private String DOCUMENTHOLIDAYSTARTDAY;
    private String DOCUMENTHOLIDAYENDDAY;
    private String DOCUMENTHOLIDAYCONTENT;
    private String DOCUMENTHOLIDAYCHECK;
    private String DOCUMENTHOLIDAYSTATUS;
    private String DOCUMENTHOLIDAYPAYMENTDAY;
    private String DOCUMENTHOLIDAYPAYMENTUSER;
    private String DOCUMENTHOLIDAYPAYMENTDEPARTMENT;
    private String DOCUMENTHOLIDAYPAYMENTUSERID;


    //DOCUMENT_TASKREPORT(업무보고서 테이블)
    private String DOCUMENTTASKREPORTNUM;
    //private String USERID;
    private String DOCUMENTTASKREPORTUSERNAME;
    private String DOCUMENTTASKREPORTUSERDEPARTMENT;
    private String DOCUMENTTASKREPORTTITLE;
    private String DOCUMENTTASKREPORTTASKNAME;
    private String DOCUMENTTASKREPORTSUBMITDAY;
    private String DOCUMENTTASKREPORTSTARTDAY;
    private String DOCUMENTTASKREPORTENDDAY;
    private String DOCUMENTTASKREPORTPLAN;
    private String DOCUMENTTASKREPORTSPECIALNOTE;
    private String DOCUMENTTASKREPORTSUGGESTIONS;
    private String DOCUMENTTASKREPORTCHECK;
    private String DOCUMENTTASKREPORTSTATUS;
    private String DOCUMENTTASKREPORTPAYMENTDAY;
    private String DOCUMENTTASKREPORTPAYMENTUSER;
    private String DOCUMENTTASKREPORTPAYMENTDEPARTMENT;
    private String DOCUMENTTASKREPORTPAYMENTUSERID;


    //DOCUMENT_RESIGNATION(사직서 테이블)
    private String DOCUMENTRESIGNATIONNUM;
    //private String USERID;
    private String DOCUMENTRESIGNATIONUSERNAME;
    private String DOCUMENTRESIGNATIONUSERDEPARTMENT;
    private String DOCUMENTRESIGNATIONUSERCREATEDAY;
    private String DOCUMENTRESIGNATIONTITLE;
    private String DOCUMENTRESIGNATIONSUBMITDAY;
    private String DOCUMENTRESIGNATIONRETIREMENTDAY;
    private String DOCUMENTRESIGNATIONREASON;
    private String DOCUMENTRESIGNATIONCHECK;
    private String DOCUMENTRESIGNATIONSTATUS;
    private String DOCUMENTRESIGNATIONPAYMENTDAY;
    private String DOCUMENTRESIGNATIONPAYMENTUSER;
    private String DOCUMENTRESIGNATIONPAYMENTDEPARTMENT;
    private String DOCUMENTRESIGNATIONPAYMENTUSERID;


    //USER
    //private String USERID;
    private String USERNAME;
    private String USERCREATEDDATE;
    private String USERROLE;


    //DEPARTMENT
    private int DEPARTMENTID;
    private String DEPARTMENTNAME;


}
